config/routes.rb
      controllers applications: 'oauth/applications',
        authorized_applications: 'oauth/authorized_applications',
        authorizations: 'oauth/authorizations',
        token_info: 'oauth/token_info',
        tokens: 'oauth/tokens'
    end
    put '/oauth/applications/:id/renew(.:format)' => 'oauth/applications#renew', as: :renew_oauth_application

    # This prefixless path is required because Jira gets confused if we set it up with a path
    # More information: https://gitlab.com/gitlab-org/gitlab/issues/6752
    scope path: '/login/oauth', controller: 'oauth/jira_dvcs/authorizations', as: :oauth_jira_dvcs do
      get :authorize, action: :new
      get :callback
      post :access_token

      match '*all', via: [:get, :post], to: proc { [404, {}, ['']] }
    end

    draw :oauth

    use_doorkeeper_openid_connect do
      controllers discovery: 'jwks'
    end

    # Add OPTIONS method for CORS preflight requests
    match '/oauth/userinfo' => 'doorkeeper/openid_connect/userinfo#show', via: :options
    match '/oauth/discovery/keys' => 'jwks#keys', via: :options
    match '/.well-known/openid-configuration' => 'jwks#provider', via: :options
    match '/.well-known/webfinger' => 'jwks#webfinger', via: :options

    match '/oauth/token' => 'oauth/tokens#create', via: :options
    match '/oauth/revoke' => 'oauth/tokens#revoke', via: :options

    match '/-/jira_connect/oauth_application_id' => 'jira_connect/oauth_application_ids#show', via: :options
    match '/-/jira_connect/subscriptions(.:format)' => 'jira_connect/subscriptions#index', via: :options
    match '/-/jira_connect/subscriptions/:id' => 'jira_connect/subscriptions#delete', via: :options

    # Sign up
    scope path: '/users/sign_up', module: :registrations, as: :users_sign_up do
      resource :welcome, only: [:show, :update], controller: 'welcome'

      Gitlab.ee do
        resource :company, only: [:new, :create], controller: 'company'
        resources :groups_projects, only: [:new, :create] do
          post :import, on: :collection
        end
        draw :verification
      end
    end

    # Search
    get 'search' => 'search#show', as: :search
    get 'search/autocomplete' => 'search#autocomplete', as: :search_autocomplete
    get 'search/count' => 'search#count', as: :search_count
    get 'search/opensearch' => 'search#opensearch', as: :search_opensearch

    Gitlab.ee do
      get 'search/aggregations' => 'search#aggregations', as: :search_aggregations
    end

    # JSON Web Token
    get 'jwt/auth' => 'jwt#auth'
    post 'jwt/auth', to: proc { [404, {}, ['']] }

    # Health check
    get 'health_check(/:checks)' => 'health_check#index', as: :health_check

    # Terraform service discovery
    get '.well-known/terraform.json' => 'terraform/services#index', as: :terraform_services

    # Begin of the /-/ scope.
    # Use this scope for all new global routes.
    scope path: '-' do
      # Autocomplete
      get '/autocomplete/users' => 'autocomplete#users'
      get '/autocomplete/users/:id' => 'autocomplete#user'
      get '/autocomplete/projects' => 'autocomplete#projects'
      get '/autocomplete/award_emojis' => 'autocomplete#award_emojis'
      get '/autocomplete/merge_request_target_branches' => 'autocomplete#merge_request_target_branches'
      get '/autocomplete/deploy_keys_with_owners' => 'autocomplete#deploy_keys_with_owners'

      Gitlab.ee do
        get '/autocomplete/project_groups' => 'autocomplete#project_groups'
        get '/autocomplete/project_routes' => 'autocomplete#project_routes'
        get '/autocomplete/namespace_routes' => 'autocomplete#namespace_routes'
        get '/autocomplete/group_subgroups' => 'autocomplete#group_subgroups'
      end

      # sandbox
      get '/sandbox/mermaid' => 'sandbox#mermaid'
      get '/sandbox/swagger' => 'sandbox#swagger'

      get '/whats_new' => 'whats_new#index'

      get 'offline' => "pwa#offline"
      get 'manifest' => "pwa#manifest", constraints: lambda { |req| req.format == :json }

      # '/-/health' implemented by BasicHealthCheck middleware
      get 'liveness' => 'health#liveness'
      get 'readiness' => 'health#readiness'
      controller :metrics do
        get 'metrics', action: :index
        get 'metrics/system', action: :system
      end
      mount Peek::Railtie => '/peek', as: 'peek_routes'

      get 'runner_setup/platforms' => 'runner_setup#platforms'

      get 'acme-challenge/' => 'acme_challenges#show'

      scope :ide, as: :ide, format: false do
        get '/', to: 'ide#index'
        get '/project', to: 'ide#index'

        scope path: 'project/:project_id', as: :project, constraints: { project_id: Gitlab::PathRegex.full_namespace_route_regex } do
          %w[edit tree blob].each do |action|
            get "/#{action}", to: 'ide#index'
            get "/#{action}/*branch/-/*path", to: 'ide#index'
            get "/#{action}/*branch/-", to: 'ide#index'
            get "/#{action}/*branch", to: 'ide#index'
          end

          get '/merge_requests/:merge_request_id', to: 'ide#index', constraints: { merge_request_id: /\d+/ }
          get '/', to: 'ide#index'
        end

        # Remote host can contain "." characters so it needs a constraint
        post 'remote/:remote_host(/*remote_path)',
          as: :remote,
          to: 'web_ide/remote_ide#index',
          constraints: { remote_host: %r{[^/?]+} }
      end

      draw :operations
      draw :jira_connect

      Gitlab.ee do
        draw :remote_development
        draw :security
        draw :smartcard
        draw :trial
        draw :trial_registration
        draw :country
        draw :country_state
        draw :subscription
        draw :llm

        scope '/push_from_secondary/:geo_node_id' do
          draw :git_http
        end
      end

      Gitlab.jh do
        draw :global_jh
      end

      if ENV['GITLAB_CHAOS_SECRET'] || Rails.env.development? || Rails.env.test?
        resource :chaos, only: [] do
          get :leakmem
          get :cpu_spin
          get :db_spin
          get :sleep
          get :kill
          get :quit
          post :gc
        end
      end

      resources :invites, only: [:show], constraints: { id: /[A-Za-z0-9_-]+/ } do
        member do
          post :accept
          match :decline, via: [:get, :post]
        end
      end

      resources :sent_notifications, only: [], constraints: { id: /\h{32}/ } do
        member do
          get :unsubscribe
        end
      end

      # Spam reports
      resources :abuse_reports, only: [:new, :create] do
        collection do
          post :add_category
        end
      end

      # JWKS (JSON Web Key Set) endpoint
      # Used by third parties to verify CI_JOB_JWT
      get 'jwks' => 'jwks#index'

      draw :snippets
      draw :profile

      post '/mailgun/webhooks' => 'mailgun/webhooks#process_webhook'

      # Deprecated route for permanent failures
      # https://gitlab.com/gitlab-org/gitlab/-/issues/362606
      post '/members/mailgun/permanent_failures' => 'mailgun/webhooks#process_webhook'

      get '/timelogs' => 'time_tracking/timelogs#index'
    end
    # End of the /-/ scope.

    concern :clusterable do
      resources :clusters, only: [:index, :show, :update, :destroy] do
        collection do
          get  :connect
          get  :new_cluster_docs
          post :create_user
        end

        resource :integration, controller: 'clusters/integrations', only: [] do
          collection do
            post :create_or_update
          end
        end

        member do
          Gitlab.ee do
            get :metrics, format: :json
            get :environments, format: :json
          end

          get :metrics_dashboard
          get :'/prometheus/api/v1/*proxy_path', to: 'clusters#prometheus_proxy', as: :prometheus_api
          get :cluster_status, format: :json
          delete :clear_cache
        end
      end
    end

    resources :groups, only: [:index, :new, :create] do
      post :preview_markdown
    end

    draw :group

    resources :projects, only: [:index, :new, :create]

    get '/projects/:id' => 'projects/redirect#redirect_from_id'

    draw :git_http
    draw :api
    draw :customers_dot
    draw :sidekiq
    draw :help
    draw :google_api
    draw :import
    draw :uploads
    draw :explore
    draw :admin
    draw :dashboard
    draw :user
    draw :project
    draw :unmatched_project

    # Issue https://gitlab.com/gitlab-org/gitlab/-/issues/210024
    scope as: 'deprecated' do
      # Issue https://gitlab.com/gitlab-org/gitlab/-/issues/223719
      get '/snippets/:id/raw',
        to: 'snippets#raw',
        format: false,
        constraints: { id: /\d+/ }

      Gitlab::Routing.redirect_legacy_paths(self, :snippets)
    end

    Gitlab.ee do
      get '/sitemap' => 'sitemap#show', format: :xml
    end

    # Creates shorthand helper methods for project resources.
    # For example; for the `namespace_project_path` this also creates `project_path`.
    #
    # TODO: We don't need the `Gitlab::Routing` module at all as we can use
    # the `direct` DSL method of Rails to define url helpers. Move all the
    # custom url helpers to use the `direct` DSL method and remove the `Gitlab::Routing`.
    # For more information: https://gitlab.com/groups/gitlab-org/-/epics/9866
    Gitlab::Application.routes.set.filter_map { |route| route.name if route.name&.include?('namespace_project') }.each do |name|
      new_name = name.sub('namespace_project', 'project')

      direct(new_name) do |project, *args|
        # This is due to a bug I've found in Rails.
        # For more information: https://gitlab.com/gitlab-org/gitlab/-/issues/299591
        args.pop if args.last == {}

        send("#{name}_url", project&.namespace, project, *args)
      end
    end

    root to: "root#index"

    get '*unmatched_route', to: 'application#route_not_found', format: false

    # Load all custom URLs definitions via `direct' after the last route

app/models/clusters/integrations/prometheus.rb
# frozen_string_literal: true

module Clusters
  module Integrations
    class Prometheus < ApplicationRecord
      include ::Clusters::Concerns::PrometheusClient
      include AfterCommitQueue

      self.table_name = 'clusters_integration_prometheus'
      self.primary_key = :cluster_id

      belongs_to :cluster, class_name: 'Clusters::Cluster', foreign_key: :cluster_id

      validates :cluster, presence: true
      validates :enabled, inclusion: { in: [true, false] }

      # Periodically checked and kept up to date for Monitor demo projects
      enum health_status: {
        unknown: 0,
        healthy: 1,
        unhealthy: 2
      }

      attr_encrypted :alert_manager_token,
        mode: :per_attribute_iv,
        key: Settings.attr_encrypted_db_key_base_32,
        algorithm: 'aes-256-gcm'

      after_initialize :set_alert_manager_token, if: :new_record?

      scope :enabled, -> { where(enabled: true) }

      after_destroy do
        run_after_commit do
          deactivate_project_integrations
        end
      end

      after_save do
        next unless enabled_before_last_save != enabled

        run_after_commit do
          if enabled
            activate_project_integrations
          else
            deactivate_project_integrations
          end
        end
      end

      def available?
        enabled?
      end

      private

      def set_alert_manager_token
        self.alert_manager_token = SecureRandom.hex
      end

      def activate_project_integrations
        ::Clusters::Applications::ActivateIntegrationWorker
          .perform_async(cluster_id, ::Integrations::Prometheus.to_param)
      end

      def deactivate_project_integrations
        ::Clusters::Applications::DeactivateIntegrationWorker
          .perform_async(cluster_id, ::Integrations::Prometheus.to_param)
      end
    end
  end
end

app/models/concerns/integrations/base_data_fields.rb
# frozen_string_literal: true

module Integrations
  module BaseDataFields
    extend ActiveSupport::Concern

    included do
      belongs_to :integration, inverse_of: self.table_name.to_sym, foreign_key: :integration_id

      validates :integration, presence: true
    end

    class_methods do
      def encryption_options
        {
          key: Settings.attr_encrypted_db_key_base_32,
          encode: true,
          mode: :per_attribute_iv,
          algorithm: 'aes-256-gcm'
        }
      end
    end

    def activated?
      !!integration&.activated?
    end

    def to_database_hash
      as_json(
        only: self.class.column_names
      ).except('id', 'service_id', 'integration_id', 'created_at', 'updated_at')
    end
  end
end

app/models/concerns/integrations/enable_ssl_verification.rb
# frozen_string_literal: true

module Integrations
  module EnableSslVerification
    extend ActiveSupport::Concern

    prepended do
      boolean_accessor :enable_ssl_verification
    end

    def initialize_properties
      super

      self.enable_ssl_verification = true if new_record? && enable_ssl_verification.nil?
    end

    def fields
      super.tap do |fields|
        url_index = fields.index { |field| field[:name].ends_with?('_url') }
        insert_index = url_index ? url_index + 1 : -1

        fields.insert(insert_index, {
          type: 'checkbox',
          name: 'enable_ssl_verification',
          title: s_('Integrations|SSL verification'),
          checkbox_label: s_('Integrations|Enable SSL verification'),
          help: s_('Integrations|Clear if using a self-signed certificate.')
        })
      end
    end
  end
end

app/models/concerns/integrations/has_data_fields.rb
# frozen_string_literal: true

module Integrations
  module HasDataFields
    extend ActiveSupport::Concern

    class_methods do
      # Provide convenient accessor methods for data fields.
      # TODO: Simplify as part of https://gitlab.com/gitlab-org/gitlab/issues/29404
      def data_field(*args)
        args.each do |arg|
          self.class_eval <<-RUBY, __FILE__, __LINE__ + 1
            unless method_defined?(arg)
              def #{arg}
                value = data_fields.send('#{arg}')
                value.nil? ? properties&.dig('#{arg}') : value
              end
            end

            def #{arg}=(value)
              @old_data_fields ||= {}
              @old_data_fields['#{arg}'] ||= #{arg} # set only on the first assignment, IOW we remember the original value only
              data_fields.send('#{arg}=', value)
            end

            def #{arg}_touched?
              @old_data_fields ||= {}
              @old_data_fields.has_key?('#{arg}')
            end

            def #{arg}_changed?
              #{arg}_touched? && @old_data_fields['#{arg}'] != #{arg}
            end

            def #{arg}_was
              return unless #{arg}_touched?
              return if data_fields.persisted? # arg_was does not work for attr_encrypted

              legacy_properties_data['#{arg}']
            end
          RUBY
        end
      end
    end

    included do
      has_one :issue_tracker_data, autosave: true, inverse_of: :integration, foreign_key: :integration_id, class_name: 'Integrations::IssueTrackerData'
      has_one :jira_tracker_data, autosave: true, inverse_of: :integration, foreign_key: :integration_id, class_name: 'Integrations::JiraTrackerData'
      has_one :zentao_tracker_data, autosave: true, inverse_of: :integration, foreign_key: :integration_id, class_name: 'Integrations::ZentaoTrackerData'

      def data_fields
        raise NotImplementedError
      end

      def data_fields_present?
        data_fields.present?
      rescue NotImplementedError
        false
      end
    end
  end
end

app/models/concerns/integrations/has_issue_tracker_fields.rb
# frozen_string_literal: true

module Integrations
  module HasIssueTrackerFields
    extend ActiveSupport::Concern

    included do
      self.field_storage = :data_fields

      field :project_url,
        required: true,
        title: -> { _('Project URL') },
        help: -> do
          s_('IssueTracker|The URL to the project in the external issue tracker.')
        end

      field :issues_url,
        required: true,
        title: -> { s_('IssueTracker|Issue URL') },
        help: -> do
          ERB::Util.html_escape(
            s_('IssueTracker|The URL to view an issue in the external issue tracker. Must contain %{colon_id}.')
          ) % {
            colon_id: '<code>:id</code>'.html_safe
          }
        end

      field :new_issue_url,
        required: true,
        title: -> { s_('IssueTracker|New issue URL') },
        help: -> do
          s_('IssueTracker|The URL to create an issue in the external issue tracker.')
        end
    end
  end
end

app/models/concerns/integrations/loggable.rb
# frozen_string_literal: true

module Integrations
  module Loggable
    def log_info(message, params = {})
      message = build_message(message, params)

      logger.info(message)
    end

    def log_error(message, params = {})
      message = build_message(message, params)

      logger.error(message)
    end

    def log_exception(error, params = {})
      Gitlab::ExceptionLogFormatter.format!(error, params)

      log_error(params[:message] || error.message, params)
    end

    def build_message(message, params = {})
      {
        integration_class: self.class.name,
        integration_id: id,
        project_id: project&.id,
        project_path: project&.full_path,
        message: message
      }.merge(params)
    end

    def logger
      Gitlab::IntegrationsLogger
    end
  end
end

app/views/shared/integrations/prometheus/_custom_metrics.html.haml
- project = local_assigns.fetch(:project)

.col-lg-3
  %p
    = s_('PrometheusService|Custom metrics require Prometheus installed on a cluster with environment scope "*" OR a manually configured Prometheus to be available.')
    = link_to s_('PrometheusService|More information'), help_page_path('operations/metrics/index.md', anchor: 'adding-custom-metrics'), target: '_blank', rel: "noopener noreferrer"

.col-lg-9
  = render Pajamas::CardComponent.new(header_options: { class: 'gl-display-flex gl-align-items-center' }, body_options: { class: 'gl-p-0' }, card_options: { class: 'gl-mb-5 custom-monitored-metrics js-panel-custom-monitored-metrics', data: { active_custom_metrics: project_prometheus_metrics_path(project), environments_data: environments_list_data, service_active: "#{integration.active}" } }) do |c|
    - c.header do
      %strong
        = s_('PrometheusService|Custom metrics')
      = gl_badge_tag 0, nil, class: 'gl-ml-2 js-custom-monitored-count'
      = link_to s_('PrometheusService|New metric'), new_project_prometheus_metric_path(project), class: 'btn gl-button btn-confirm gl-ml-auto js-new-metric-button hidden'
    - c.body do
      .flash-container.hidden
        .flash-warning
          .flash-text
      .loading-metrics.js-loading-custom-metrics
        %p.m-3
          = gl_loading_icon(inline: true, css_class: 'metrics-load-spinner')
          = s_('PrometheusService|Finding custom metrics...')
      .empty-metrics.hidden.js-empty-custom-metrics
        %p.text-tertiary.m-3.js-no-active-integration-text.hidden
          = s_('PrometheusService|Enable Prometheus to define custom metrics, using either option above')
        %p.text-tertiary.m-3.js-new-metric-text.hidden
          = s_('PrometheusService|No custom metrics have been created. Create one using the button above')
      %ul.list-unstyled.metrics-list.hidden.js-custom-metrics-list

app/views/shared/integrations/prometheus/_help.html.haml
- if @project
  = render 'shared/prometheus_configuration_banner', project: @project, integration: integration, header_tag: :h4
  %hr

%h4.gl-mb-3
  = s_('PrometheusService|Manual configuration')
%p
  = s_('PrometheusService|Auto configuration settings are used unless you override their values here.')

app/views/shared/integrations/prometheus/_metrics.html.haml
- project = local_assigns.fetch(:project)

= render 'shared/integrations/prometheus/custom_metrics', project: project, integration: integration

.col-lg-3
  %p
    = s_('PrometheusService|Common metrics are automatically monitored based on a library of metrics from popular exporters.')
    = link_to s_('PrometheusService|More information'), help_page_path('user/project/integrations/prometheus'), target: '_blank', rel: "noopener noreferrer"

.col-lg-9
  = render Pajamas::CardComponent.new(body_options: { class: 'gl-p-0' }, card_options: { class: 'gl-mb-5 js-panel-monitored-metrics', data: { active_metrics: active_common_project_prometheus_metrics_path(project, :json), metrics_help_path: help_page_path('user/project/integrations/prometheus_library/index') }}) do |c|
    - c.header do
      %strong
        = s_('PrometheusService|Common metrics')
        = gl_badge_tag 0, nil, class: 'js-monitored-count'
    - c.body do
      .loading-metrics.js-loading-metrics
        %p.m-3
          = gl_loading_icon(inline: true, css_class: 'metrics-load-spinner')
          = s_('PrometheusService|Finding and configuring metrics...')
      .empty-metrics.hidden.js-empty-metrics
        %p.text-tertiary.m-3
          = s_('PrometheusService|Waiting for your first deployment to an environment to find common metrics')
      %ul.list-unstyled.metrics-list.hidden.js-metrics-list

  = render Pajamas::CardComponent.new(body_options: { class: 'hidden gl-p-0' }, card_options: { class: 'hidden js-panel-missing-env-vars' }) do |c|
    - c.header do
      = sprite_icon('chevron-lg-right', css_class: 'panel-toggle js-panel-toggle-right')
      = sprite_icon('chevron-lg-down', css_class: 'panel-toggle js-panel-toggle-down hidden')
      = s_('PrometheusService|Missing environment variable')
      = gl_badge_tag 0, nil, class: 'js-env-var-count'
    - c.body do
      .flash-container
        .flash-notice
          .flash-text
            = html_escape(s_("PrometheusService|To set up automatic monitoring, add the environment variable %{variable} to exporter's queries.")) % { variable: "<code>$CI_ENVIRONMENT_SLUG</code>".html_safe }
            = link_to s_('PrometheusService|More information'), help_page_path('operations/metrics/dashboards/variables.md', anchor: 'query-variables')
      %ul.list-unstyled.metrics-list.js-missing-var-metrics-list

app/views/shared/integrations/prometheus/_show.html.haml
.row
  .col-lg-3
    %h4.gl-mt-0
      = s_('PrometheusService|Metrics')

.row.gl-mb-3.prometheus-metrics-monitoring.js-prometheus-metrics-monitoring
  = render 'shared/integrations/prometheus/metrics', project: @project, integration: integration